config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :stocks, only: [ :show , :new, :create ,:edit,:update ,:destroy] do
    member do
      get :buy
      get :sell
    end
  end
  resources :dividends,only: [ :show , :new, :create ,:edit,:update ,:destroy]
  resources :blands, only: [ :show , :new, :create ,:edit,:update ,:destroy] 
  resources :users, only: [:show, :new, :create ,:edit ,:update] do
    member do
      get :blands
      get :blandedits
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :blands
  has_many :type_names, through: :blands
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit ,:update]
  before_action :correct_user, only: [:show,:edit,:update,:blands,:blandedits]
  def show
    @user=User.find(params[:id])
    @blands=@user.blands.page(params[:page]).per(2)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '名前 は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '名前 は更新されませんでした'
      render :edit
    end
  end
  
  def blands
    @mybland='blands'
    @user=User.find(params[:id])
    @blands=@user.blands.order(id: :desc).page(params[:page]).per(10)
  end
  
  def blandedits
    @mybland='blandedits'
    @user=User.find(params[:id])
    @blands=@user.blands.order(id: :desc).page(params[:page]).per(10)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_blands.html.erb
<% if @mybland==='blands' %>
  <%= link_to new_bland_path, class: 'btn btn-primary' do %>
    <span>銘柄登録</span>
  <% end %>    
  <%= link_to blandedits_user_path(current_user), class: 'btn btn-outline-warning' do %>
    <span>編集</span>
  <% end %> 

<% else %>

  <%= link_to blands_user_path(current_user), class: 'btn btn-outline-warning' do %>
    <span>戻る</span>
  <% end %>
  
<% end %>



<ul class="list-unstyled">
  <% blands.each do |bland| %>
    <li class="media mb-3">
      <div class="media-body">
        <div class="row">
          <div class="col-sm-4">
            (銘柄名:<%= bland.name %>)
            (銘柄コード:<%= bland.code %>)            
          </div>
          <% if @mybland==='blands' %>             
          <div class="col-sm-4">
            <div class="text-right">
              <%= link_to buy_stock_path(bland.id), class: 'btn btn-success' do %>
                <span>銘柄買記録</span>
              <% end %>          
              <%= link_to sell_stock_path(bland.id), class: 'btn btn-danger' do %>
                <span>銘柄売記録</span>
              <% end %>  
            </div>                
            <table class="table table-sm"> 
              <tr><th>株数・口</th><th>金額</th><th>取引</th></tr>              
              <% bland.stocks.each do |stock| %>
                <% case stock.buying_and_selling
                   when 0 %>
                    <% buysell = "買" %>
                <% when 1 %>
                    <% buysell = "売" %>                   
                <% end %>
                <tr>
                  <td><%= stock.number %></td><td><%= stock.money %></td><td><%= buysell %></td>
                    <td>
                     <%= link_to edit_stock_path(stock), class: 'btn btn-outline-warning btn-sm' do %>
                      <i class="far fa-edit"></i>
                      <span>編集</span>
                    <% end %>                       
                  </td>
                </tr>
                
              <% end %> 
              <tr><th>合計</th><th></th><th></th><th></th></tr>                 
            </table>
          </div>
          <div class="col-sm-4">
            <div class="text-right">
              <%= link_to new_dividend_path(bland.id), class: 'btn btn-warning' do %>
                <span>配当金記録</span>
              <% end %>
            </div>               
            <table class="table table-sm"> 
              <tr><th></th><th>配当金</th><th>配当月</th></tr>  
              <% bland.dividends.each do |dividend| %>
                <tr>
                  <td></td><td><%= dividend.money %></td><td><%= dividend.month %></td>
                  <td>
                     <%= link_to edit_dividend_path(dividend), class: 'btn btn-outline-warning btn-sm' do %>
                      <i class="far fa-edit"></i>
                      <span>編集</span>
                    <% end %>                       
                  </td>
                </tr>
              
              <% end %>
              <tr><th>合計</th><th></th><th></th><th></th></tr>  
            </table> 
          </div>
          <% else %> 
            <div class="col-sm-8">
              <div class="text-right">
                <%= link_to edit_bland_path(bland), class: 'btn btn-success' do %>
                  <i class="far fa-edit"></i>
                  <span>編集</span>
                <% end %>
                <%= link_to bland, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' do %>
                  <i class="far fa-trash-alt"></i>
                  <span>削除</span>
                <% end %>
              </div>              
            </div>
          <% end %>            
        </div>
      </div>
    </li>
  <% end %>
  <%=paginate blands %>
</ul>

app/views/users/_navigationtab.html.erb
<div class="row">
  <aside class="col-sm-2">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= current_user.name %>
        </h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(current_user, { size: 300 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-10">
    <ul class="nav nav-tabs nav-fill">
      <li class="nav-item">
        <a href="<%= blands_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(blands_user_path(current_user)) %>">ポートフォリオ</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">配当金カレンダー・グラフ</a>
      </li>
    </ul>
    <%= render myrender, locals %>
  </div>
</div>

app/views/users/blandedits.html.erb
<%= render 'navigationtab' , myrender:'blands', locals: {blands: @blands} %>

app/views/users/blands.html.erb
<%= render 'navigationtab' , myrender:'blands', locals: {blands: @blands} %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h2>編集画面</h2>
    <%= form_with(model:@user,local:true) do |f| %>      
      <div class="form-group">
        <%= f.label :name ,'名前' %>
        <%= f.text_field :name, class: 'form-control' %>      
      </div>
      <%= f.submit '登録',class: 'btn btn-primary btn-block'  %>    
    <% end %>  
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'navigationtab' , myrender:'blands', locals: {blands: @blands} %>