config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :stocks, only: [ :show , :new, :create ,:edit,:update ,:destroy] do
    member do
      get :buy
      get :sell
    end
  end
  resources :dividends,only: [ :show , :new, :create ,:edit,:update ,:destroy]
  resources :blands, only: [ :show , :new, :create ,:edit,:update ,:destroy] 
  resources :users, only: [:show, :new, :create ,:edit ,:update] do
    member do
      get :blands
      get :blandedits
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<% if logged_in? %>

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= current_user.name %>
        </h3>
        <p><%=link_to '編集',edit_user_path(current_user) %></p>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(current_user, { size: 300 }) %>" alt="">
      </div>
    </div>
  </aside>

  <div class="col-sm-8">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><h3>名前</h3></li>
        <li class="list-group-item"><h3>資産額</h3></li>
        <li class="list-group-item"><h3>損益額</h3></li>
      </ul>
    </div>
  </div>


<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>資産運用</h1>
        <%= link_to '今すぐサインアップ!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>