config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :stocks, only: [ :show , :new, :create ,:edit,:update ,:destroy] do
    member do
      get :buy
      get :sell
    end
  end
  resources :dividends,only: [ :show , :new, :create ,:edit,:update ,:destroy]
  resources :blands, only: [ :show , :new, :create ,:edit,:update ,:destroy] 
  resources :users, only: [:show, :new, :create ,:edit ,:update] do
    member do
      get :blands
      get :blandedits
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bland.rb
class Bland < ApplicationRecord
  before_save { self.code.upcase!}
  validates :name, presence: true, length: { maximum: 50 }
  validates :code, presence: true, length: { in: 4..5 },
                    format:{with:/\A\d{4}|[a-zA-Z]{4,5}\Z/}
  belongs_to :user
  belongs_to :type_name
  has_many :stocks, dependent: :destroy
  has_many :dividends, dependent: :destroy
end

app/models/buysell.rb
class Buysell < ApplicationRecord
end

app/models/dividend.rb
class Dividend < ApplicationRecord
  validates :money , presence: true
  belongs_to :bland
end

app/models/month.rb
class Month < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :number, presence: true
  validates :money , presence: true
  belongs_to :bland
end

app/models/type_name.rb
class TypeName < ApplicationRecord
  has_many :blands
  has_many :users, through: :blands
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :blands
  has_many :type_names, through: :blands
end

app/controllers/blands_controller.rb
class BlandsController < ApplicationController
  before_action :correct_user, only: [:edit,:update,:destroy]
  def create
    @type_names = TypeName.all
    @bland=current_user.blands.build(bland_params)
    if @bland.save
      flash[:success] = '銘柄を登録しました。'
      redirect_to blands_user_path(current_user)
    else
      @blands=current_user.blands.order(id: :desc).page(params[:page])
      flash.now[:danger] = '銘柄の登録に失敗しました。'
      render :new
    end
  end

  def new
    @type_names = TypeName.all    
    @user=User.find_by(params[:id])
    @bland = current_user.blands.build
  end

  def edit
    @type_names = TypeName.all    
    @user=User.find_by(params[:id])
    @bland=Bland.find(params[:id])
  end

  def update
    @type_names = TypeName.all
    @bland=current_user.blands.find(params[:id])
    if @bland.update(bland_params)
      flash[:success] = '銘柄は正常に更新されました'
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = '銘柄は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @bland=current_user.blands.find(params[:id])
    @bland.destroy
    flash[:success] = '銘柄は正常に削除されました'
    redirect_back(fallback_location: root_path) 
  end
   private

  def bland_params
    params.require(:bland).permit(:name,:code,:type_name_id)
  end
  
  def correct_user

    @bland = current_user.blands.find_by(id: params[:id])
    unless @bland
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to blands_user_path(current_user)
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :bland_correct_user,only:[:buy,:sell]
  def new
  end

  def edit
    @buysell=Buysell.all
    @stock=Stock.find(params[:id])
    @bland=Bland.find(@stock.bland_id)
  end

  def update
    @stock=Stock.find(params[:id])    
    if @stock.update(stock_params)
      flash[:success] = '正常に更新されました'
      redirect_to blands_user_path(current_user)
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def create
    @bland=Bland.find(params[:stock][:bland_id])
    @stock=@bland.stocks.build(stock_params)
    if @stock.save
      flash[:success] = '登録しました。'
      redirect_to blands_user_path(current_user)
    else
     @blands=current_user.blands.order(id: :desc).page(params[:page])
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end

  def destroy
    @stock=Stock.find(params[:id])
    @stock.destroy
    flash[:success] = '正常に削除されました'
    redirect_to blands_user_path(current_user)

  end
  
  def buy
    @buysell=Buysell.all
    @user=User.find(current_user.id)
    @bland=Bland.find(params[:id])
    @stock=@bland.stocks.build(bland_id:params[:id],buying_and_selling:0)
  end
  
  def sell
    @buysell=Buysell.all
    @user=User.find(current_user.id)
    @bland=Bland.find(params[:id])
    @stock=@bland.stocks.build(bland_id:params[:id],buying_and_selling:1)
  end
  
  private
  
  def stock_params
    params.require(:stock).permit(:number,:money,:buying_and_selling)
  end
  def bland_correct_user
    @bland=Bland.find(params[:id])
    unless @bland.user_id===current_user.id
      redirect_to root_url
    end
  end
  
  def correct_user
    @user=Bland.find(Stock.find(params[:id]).bland_id)
    unless @user.user_id===current_user.id
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit ,:update]
  before_action :correct_user, only: [:show,:edit,:update,:blands,:blandedits]
  def show
    @user=User.find(params[:id])
    @blands=@user.blands.page(params[:page]).per(2)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '名前 は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '名前 は更新されませんでした'
      render :edit
    end
  end
  
  def blands
    @mybland='blands'
    @user=User.find(params[:id])
    @blands=@user.blands.order(id: :desc).page(params[:page]).per(10)
  end
  
  def blandedits
    @mybland='blandedits'
    @user=User.find(params[:id])
    @blands=@user.blands.order(id: :desc).page(params[:page]).per(10)
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blands_helper.rb
module BlandsHelper
  def current_bland(id)
    @current_bland ||= Bland.find(params[:id])
  end
end

app/helpers/dividends_helper.rb
module DividendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <% if logged_in? %>
      <%= link_to '資産運用', root_path, class:'navbar-brand'%>
    <% else %>
      <a class="navbar-brand" href="/">資産運用</a>    
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to '銘柄登録', new_bland_path(@bland) %></li>
              <li class="dropdown-divider"></li>              
              <li class="dropdown-item"><%= link_to 'ポートフォリオ', blands_user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to '配当金カレンダー・グラフ', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'ユーザ情報', root_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'サインアップ', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>資産運用</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>